-- Additional content for CulturaFlow to have more cards
-- Execute this after the main seed data

INSERT INTO public.cultural_content (title, description, content_type, category, subcategory, difficulty, duration_minutes, points_reward, image_url, facts, tags, language, region, is_trending) VALUES

-- More Arte content
('Pablo Picasso: El Genio del Cubismo', 'Conoce la vida y obra del artista que revolucionó el arte del siglo XX con su estilo único y su constante evolución artística.', 'article', 'arte', 'pintura', 'intermediate', 10, 18, 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500', ARRAY['Pintó más de 50,000 obras en su vida', 'Creó el movimiento cubista junto a Braque', 'Su obra "Les Demoiselles d''Avignon" cambió el arte para siempre', 'Vivió 91 años y nunca dejó de crear'], ARRAY['picasso', 'cubismo', 'arte-moderno', 'siglo-xx'], 'es', 'España', true),

('Diego Velázquez: El Maestro del Realismo', 'Explora la técnica magistral de Velázquez, pintor de la corte española que creó algunas de las obras más admiradas de la historia.', 'article', 'arte', 'pintura', 'advanced', 12, 22, 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500', ARRAY['Las Meninas es considerada la obra maestra de la pintura', 'Fue pintor oficial de Felipe IV', 'Influyó enormemente en los impresionistas', 'Manet lo llamó "el pintor de pintores"'], ARRAY['velazquez', 'siglo-oro', 'realismo', 'las-meninas'], 'es', 'España', false),

('El Muralismo Mexicano: Arte y Revolución', 'Descubre cómo Diego Rivera, Orozco y Siqueiros transformaron los muros en lienzos que narraban la historia del pueblo mexicano.', 'article', 'arte', 'pintura', 'intermediate', 13, 20, 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500', ARRAY['Surgió después de la Revolución Mexicana', 'Buscaba crear un arte accesible para todos', 'Los "Tres Grandes": Rivera, Orozco y Siqueiros', 'Los murales decoran edificios públicos'], ARRAY['muralismo', 'mexico', 'rivera', 'revolucion'], 'es', 'México', true),

-- More Historia content
('La Alhambra de Granada: Joya del Islam en España', 'Recorre los palacios nazaríes y descubre cómo ocho siglos de presencia musulmana dejaron su huella en la arquitectura española.', 'article', 'historia', 'medieval', 'intermediate', 11, 19, 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500', ARRAY['Construida entre los siglos XIII y XIV', 'Significa "La Roja" en árabe', 'Patrimonio de la Humanidad desde 1984', 'Inspiró a Washington Irving y otros escritores románticos'], ARRAY['alhambra', 'granada', 'nazaries', 'al-andalus'], 'es', 'Andalucía', true),

('Simon Bolívar: El Libertador de América', 'La vida del héroe que liberó seis países sudamericanos del dominio español y soñó con una América unida.', 'article', 'historia', 'independencia', 'intermediate', 14, 24, 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500', ARRAY['Liberó Venezuela, Colombia, Ecuador, Perú, Bolivia y Panamá', 'Soñó con crear una gran confederación americana', 'Murió en la pobreza a los 47 años', 'Es llamado "El Libertador" en toda América'], ARRAY['bolivar', 'independencia', 'libertador', 'venezuela'], 'es', 'Venezuela', false),

('La Guerra Civil Española: Una Tragedia Nacional', 'El conflicto que dividió España entre 1936 y 1939, ensayo de la Segunda Guerra Mundial y trauma nacional que marcó generaciones.', 'article', 'historia', 'siglo-xx', 'advanced', 15, 25, 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500', ARRAY['Duró de 1936 a 1939', 'Fue un ensayo para la Segunda Guerra Mundial', 'Murieron más de 500,000 personas', 'Inspiró obras como Guernica de Picasso'], ARRAY['guerra-civil', 'espana', 'franco', 'republica'], 'es', 'España', false),

-- More Música content
('Paco de Lucía: Revolución Flamenca', 'Conoce al guitarrista que llevó el flamenco a audiencias mundiales y lo fusionó con jazz, rock y música clásica.', 'audio', 'musica', 'flamenco', 'intermediate', 8, 16, 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500', ARRAY['Grabó más de 30 álbumes', 'Colaboró con John McLaughlin y Al Di Meola', 'Ganó el Grammy Latino póstumo', 'Entre Dos Aguas es su tema más famoso'], ARRAY['paco-lucia', 'flamenco', 'guitarra', 'fusion'], 'es', 'España', true),

('La Nueva Canción Latinoamericana', 'El movimiento musical que combinó protesta social y tradición folclórica, con Víctor Jara, Mercedes Sosa y Violeta Parra.', 'audio', 'musica', 'folclore', 'intermediate', 12, 20, 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500', ARRAY['Surgió en los años 60 y 70', 'Combinaba música tradicional con protesta social', 'Víctor Jara fue asesinado durante el golpe de Pinochet', 'Mercedes Sosa fue llamada "La Negra"'], ARRAY['nueva-cancion', 'victor-jara', 'mercedes-sosa', 'protesta'], 'es', 'Latinoamérica', false),

('El Son Cubano: Raíz de la Salsa', 'Descubre cómo este género nacido en Cuba se extendió por el mundo y dio origen a la salsa, el mambo y otros ritmos caribeños.', 'audio', 'musica', 'caribe', 'beginner', 9, 15, 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500', ARRAY['Nació en el oriente de Cuba', 'Combina instrumentos africanos y españoles', 'Benny Moré fue el "Bárbaro del Ritmo"', 'Buena Vista Social Club lo revivió mundialmente'], ARRAY['son-cubano', 'cuba', 'benny-more', 'buena-vista'], 'es', 'Cuba', true),

-- More Literatura content
('Jorge Luis Borges: Laberintos de la Mente', 'Explora el universo literario del escritor argentino que creó mundos infinitos en cuentos perfectos y ensayos filosóficos.', 'article', 'literatura', 'cuento', 'advanced', 13, 23, 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500', ARRAY['Escribió principalmente cuentos y ensayos', 'Era ciego desde los 55 años', 'Creó el concepto de literatura fantástica moderna', 'Nunca ganó el Nobel pero influyó en toda la literatura mundial'], ARRAY['borges', 'argentina', 'fantasia', 'laberintos'], 'es', 'Argentina', true),

('Octavio Paz: Poeta y Pensador', 'El único mexicano en ganar el Premio Nobel de Literatura, explorador de la identidad mexicana y universal poeta del amor.', 'article', 'literatura', 'poesia', 'intermediate', 11, 19, 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500', ARRAY['Ganó el Nobel de Literatura en 1990', 'Escribió "El Laberinto de la Soledad"', 'Fue embajador de México en India', 'Fundó las revistas Plural y Vuelta'], ARRAY['octavio-paz', 'mexico', 'nobel', 'soledad'], 'es', 'México', false),

-- More Gastronomía content
('Ceviche: El Plato Bandera del Perú', 'Descubre la historia y preparación del ceviche peruano, plato que conquista paladares en todo el mundo.', 'article', 'gastronomia', 'platos-tipicos', 'beginner', 7, 12, 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=500', ARRAY['Se "cocina" el pescado con ácido cítrico', 'Patrimonio Cultural de la Nación Peruana', 'Cada región tiene su variante', 'Se debe consumir fresco, recién preparado'], ARRAY['ceviche', 'peru', 'pescado', 'limon'], 'es', 'Perú', true),

('Empanadas: Sabores de América Latina', 'Un recorrido por las diferentes versiones de empanadas en América Latina, desde Argentina hasta Venezuela.', 'article', 'gastronomia', 'platos-tipicos', 'beginner', 8, 14, 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=500', ARRAY['Cada país tiene su versión característica', 'Pueden ser horneadas o fritas', 'Los rellenos varían según la región', 'Patrimonio gastronómico de varios países'], ARRAY['empanadas', 'latinoamerica', 'tradicion', 'regional'], 'es', 'Latinoamérica', false),

-- More Tradiciones content
('Carnaval de Barranquilla: Fiesta del Caribe', 'Vive la alegría del carnaval más importante de Colombia, Patrimonio de la Humanidad lleno de música, danza y color.', 'article', 'tradiciones', 'carnavales', 'beginner', 10, 16, 'https://images.unsplash.com/photo-1509715513011-e394f0cb20c4?w=500', ARRAY['Se celebra en febrero o marzo', 'Patrimonio Oral e Inmaterial de la Humanidad', 'La Batalla de Flores es el evento principal', 'Combina tradiciones africanas, indígenas y españolas'], ARRAY['carnaval', 'barranquilla', 'colombia', 'caribe'], 'es', 'Colombia', true),

('La Tomatina de Buñol: Guerra de Tomates', 'La fiesta más divertida de España donde miles de personas se lanzan tomates en las calles de un pequeño pueblo valenciano.', 'article', 'tradiciones', 'festivales', 'beginner', 6, 10, 'https://images.unsplash.com/photo-1509715513011-e394f0cb20c4?w=500', ARRAY['Se celebra el último miércoles de agosto', 'Comenzó en 1945 con una pelea de jóvenes', 'Se usan más de 150,000 kilos de tomates', 'Dura exactamente una hora'], ARRAY['tomatina', 'bunol', 'valencia', 'tomates'], 'es', 'España', false),

-- More Geografía content
('Titicaca: El Lago Sagrado de los Incas', 'Explora el lago navegable más alto del mundo, frontera entre Perú y Bolivia, lleno de historia y tradiciones milenarias.', 'article', 'geografia', 'lagos', 'intermediate', 9, 17, 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=500', ARRAY['Está a 3,812 metros sobre el nivel del mar', 'Las islas flotantes están hechas de totora', 'Los uros han vivido allí por más de 500 años', 'Según la leyenda, de aquí surgieron los incas'], ARRAY['titicaca', 'peru', 'bolivia', 'uros'], 'es', 'Perú-Bolivia', true),

('Torres del Paine: Patagonia Chilena', 'Descubre uno de los paisajes más espectaculares del mundo en el extremo sur de Chile, hogar de glaciares y pumas.', 'article', 'geografia', 'parques', 'intermediate', 11, 19, 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=500', ARRAY['Parque Nacional desde 1959', 'Reserva de la Biosfera de la UNESCO', 'Hogar del puma patagónico', 'Las Torres son formaciones de granito de 2,800 metros'], ARRAY['torres-paine', 'chile', 'patagonia', 'pumas'], 'es', 'Chile', false);

-- Add some more variety content
INSERT INTO public.cultural_content (title, description, content_type, category, difficulty, duration_minutes, points_reward, tags, language, is_trending) VALUES
('Quiz: Capitales de América Latina', 'Pon a prueba tus conocimientos geográficos con las capitales de los países latinoamericanos.', 'quiz', 'geografia', 'beginner', 5, 15, ARRAY['geografia', 'capitales', 'latinoamerica', 'quiz'], 'es', false),
('Quiz: Grandes Escritores del Boom Latinoamericano', 'Demuestra cuánto sabes sobre García Márquez, Vargas Llosa, Cortázar y otros grandes del Boom.', 'quiz', 'literatura', 'intermediate', 7, 20, ARRAY['literatura', 'boom-latinoamericano', 'quiz', 'autores'], 'es', true),
('Quiz: Arte Precolombino', 'Explora tus conocimientos sobre las culturas Maya, Azteca e Inca a través de su arte y arquitectura.', 'quiz', 'arte', 'intermediate', 6, 18, ARRAY['arte', 'precolombino', 'maya', 'inca', 'azteca'], 'es', false);